# sklearn.linear_model.LogisticRegression

### https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

# sover为逻辑回归损失函数的优化算法

### https://zhuanlan.zhihu.com/p/32626442
### https://zhuanlan.zhihu.com/p/35182003

 # sklearn.metrics.roc_curve

### https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html#sklearn.metrics.roc_curve

# np.set_printoptions(threshold=np.inf)

### https://blog.csdn.net/GZHermit/article/details/72716619
### https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html

# predict_proba

In [8]:
from sklearn.linear_model import LogisticRegression
import numpy as np

x_train = np.array([[1,2,3],
                    [1,3,4],
                    [2,1,2],
                    [4,5,6],
                    [3,5,3],
                    [1,7,2]])
 
y_train = np.array([3, 3, 3, 2, 2, 2])
 
x_test = np.array([[2,2,2],
                   [3,2,6],
                   [1,7,4]])
clf = LogisticRegression()
clf.fit(x_train,y_train)


# 返回预测标签
print(clf.predict(x_test))

# 返回预测标签的概率
print(clf.predict_proba(x_test))

#返回预测为3的概率
print(clf.predict_proba(x_test)[:,1])
print(clf.predict_proba(x_test)[:,0])

[3 3 2]
[[0.12605725 0.87394275]
 [0.22954195 0.77045805]
 [0.92951973 0.07048027]]
[0.87394275 0.77045805 0.07048027]
[0.12605725 0.22954195 0.92951973]


In [17]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder

grd = GradientBoostingClassifier(n_estimators=3)
grd.fit(x_train,y_train)

print(grd.apply(x_train)[:2])
print(grd.apply(x_train)[:,:,0])
grd_enc = OneHotEncoder(categories='auto')
grd_enc.fit(grd.apply(x_train)[:,:,0])
print(grd_enc.transform(grd.apply(x_train)[:,:,0]))

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
  (0, 0)	1.0
  (0, 2)	1.0
  (0, 4)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (2, 0)	1.0
  (2, 2)	1.0
  (2, 4)	1.0
  (3, 1)	1.0
  (3, 3)	1.0
  (3, 5)	1.0
  (4, 1)	1.0
  (4, 3)	1.0
  (4, 5)	1.0
  (5, 1)	1.0
  (5, 3)	1.0
  (5, 5)	1.0
